server:
  port: 8020

  #应用名称（nacos会将该名称作为服务名称）
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8847
      discovery:
        username: nacos
        password: nacos
        namespace: public
# springboot 默认的日志级别是info，feign的debug日志就不会输出
logging:
  level:
    com.xz.order.feign: debug
# feign 日志局部配置
feign:
  client:
    config:
      # 服务名
      product-service:
        # 日志级别
        loggerLevel: BASIC
        # 连接超时时间 s
        connectTimeout: 5000
        # 请求处理超时时间 s
        readTimeout: 10000
        #自定义拦截器
        requestInterceptors[0]:
          com.xz.order.interceptor.feign.CustomFeignInterceptor

stock-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule #权重策略
ribbon:
  eager-load:
    # 开启饥饿加载
    enabled: true
    # 配置stock-service 使用饥饿加载，多个使用逗号相隔
    clients: stock-service
